# Generated by Django 3.1.4 on 2020-12-24 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201224_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
