# Generated by Django 3.1.4 on 2021-01-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
