
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightUMINUSrightEXPONENTCOMMENT DIVIDE EXPONENT IGNORE LINECONT LPAREN MINUS NEWLINE NUMBER PLUS RPAREN TIMESstatement : expressionexpexponent : NUMBER\n            | MINUS NUMBER %prec UMINUSnum : NUMBER\n            | MINUS NUMBER %prec UMINUSexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expression\n                  | expression EXPONENT expexponent\n                  | LPAREN expression RPARENexpression : num'
    
_lr_action_items = {'LPAREN':([0,4,7,8,9,10,],[4,4,4,4,4,4,]),'NUMBER':([0,3,4,7,8,9,10,11,20,],[6,12,6,6,6,6,6,19,22,]),'MINUS':([0,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,],[3,8,3,-12,-4,3,3,3,3,20,-5,8,-6,-7,-8,-9,-10,-2,-11,-3,]),'$end':([1,2,5,6,12,14,15,16,17,18,19,21,22,],[0,-1,-12,-4,-5,-6,-7,-8,-9,-10,-2,-11,-3,]),'PLUS':([2,5,6,12,13,14,15,16,17,18,19,21,22,],[7,-12,-4,-5,7,-6,-7,-8,-9,-10,-2,-11,-3,]),'TIMES':([2,5,6,12,13,14,15,16,17,18,19,21,22,],[9,-12,-4,-5,9,9,9,-8,-9,-10,-2,-11,-3,]),'DIVIDE':([2,5,6,12,13,14,15,16,17,18,19,21,22,],[10,-12,-4,-5,10,10,10,-8,-9,-10,-2,-11,-3,]),'EXPONENT':([2,5,6,12,13,14,15,16,17,18,19,21,22,],[11,-12,-4,-5,11,11,11,11,11,-10,-2,-11,-3,]),'RPAREN':([5,6,12,13,14,15,16,17,18,19,21,22,],[-12,-4,-5,21,-6,-7,-8,-9,-10,-2,-11,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,4,7,8,9,10,],[2,13,14,15,16,17,]),'num':([0,4,7,8,9,10,],[5,5,5,5,5,5,]),'expexponent':([11,],[18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','main.py',158),
  ('expexponent -> NUMBER','expexponent',1,'p_expexponent_number','main.py',166),
  ('expexponent -> MINUS NUMBER','expexponent',2,'p_expexponent_number','main.py',167),
  ('num -> NUMBER','num',1,'p_num_uminus','main.py',178),
  ('num -> MINUS NUMBER','num',2,'p_num_uminus','main.py',179),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','main.py',190),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','main.py',191),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','main.py',192),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','main.py',193),
  ('expression -> expression EXPONENT expexponent','expression',3,'p_expression_binop','main.py',194),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_binop','main.py',195),
  ('expression -> num','expression',1,'p_expression_number','main.py',219),
]
